"""Generate compact coastline polylines from Natural Earth's public-domain 110m GeoJSON.
Usage: python3 tools/make_coastlines.py /path/to/ne_110m_coastline.geojson
Source: https://github.com/nvkelso/natural-earth-vector/blob/master/geojson/ne_110m_coastline.geojson
"""
import json
import math
import pathlib
import sys


def simplify(points, epsilon=0.38):
    if len(points) < 3:
        return points
    ax, ay = points[0]
    bx, by = points[-1]
    dx, dy = bx - ax, by - ay
    den = dx * dx + dy * dy
    def distance(p):
        t = max(0, min(1, ((p[0]-ax)*dx + (p[1]-ay)*dy) / den)) if den else 0
        return math.hypot(p[0]-ax-t*dx, p[1]-ay-t*dy)
    index = max(range(1, len(points)-1), key=lambda i: distance(points[i]))
    if distance(points[index]) <= epsilon:
        return [points[0], points[-1]]
    return simplify(points[:index+1])[:-1] + simplify(points[index:])


segments = []
for feature in json.loads(pathlib.Path(sys.argv[1]).read_text())['features']:
    geometry = feature['geometry']
    lines = [geometry['coordinates']] if geometry['type'] == 'LineString' else geometry['coordinates']
    for line in lines:
        current = []
        for lon, lat, *_ in line:
            if lat < 0:
                if len(current) > 1:
                    segments.append(simplify(current))
                current = []
            else:
                current.append((lon, lat))
        if len(current) > 1:
            segments.append(simplify(current))
output = ['// Generated by tools/make_coastlines.py; Natural Earth, public domain.',
          '#pragma once', '#include <cstdint>', 'namespace aurora {',
          'constexpr int16_t coastline[][2] = {']
for segment in segments:
    output.extend(f'  {{{round(lon*10)}, {round(lat*10)}}},' for lon, lat in segment)
    output.append('  {32767, 32767},')
output.extend(['};', '}'])
pathlib.Path('include/aurora/coastlines.h').write_text('\n'.join(output)+'\n')
print(f'Generated {sum(map(len, segments))} coast points')
